server:
  port: 9001
spring:
  application:
    name: tensquare-base
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://129.28.155.7:3306/tensquare_base?characterEncoding=utf-8
    password: root
    username: root
  jpa:
    database: mysql
    show-sql: true
